Task5 file loading
phantom-profile/rails-questions-n-answers pull request #5
Opened 2021-09-06 16:41 UTC by phantom-profile

2021-09-06 19:04 UTC, VidgarVii requested changes

2021-09-06 19:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>        redirect_to questions_path, alert: 'it is not your question'
если для совершении операции нет прав, то принято отдавать статус forbidden

2021-09-06 19:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
1 delete_attachment у тебя дублируется
2 в контроллере вопросов  происходит удаление другого ресурса - attachment
Создай для него отдельный контроллер с методом destroy и удаляй файл там зная его id. Так же как удаляешь вопрос или ответ
соответственно у тебя еще и сократится кол-во тестов

2021-09-07 13:45 UTC, vkurennov approved these changes

2021-09-07 13:45 UTC, vkurennov commented on app/controllers/attachments_controller.rb
> +    @file = ActiveStorage::Blob.find_signed(params[:id])
можно проще находить файл `ActiveStorage::Attachament.find`

2021-09-07 14:46 UTC, merged